version: "3.9"

services:
  app:
    build: .
    deploy:
      replicas: 3
    depends_on:
      - mongo
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATA_MONGODB_URI=mongodb://url:url123@mongo:27017/db_test
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    expose:
      - "8080"

  nginx:
    image: nginx:alpine
    container_name: nginx-loadbalancer
    ports:
      - "8080:80"   # 👈 public entry point
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: url
      MONGO_INITDB_ROOT_PASSWORD: url123
      MONGO_INITDB_DATABASE: db_test
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
